---
- name: Ensure users are created
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    shell: "/bin/bash"
    state: present
  with_items: "{{ users }}"

- name: Ensure ssh keys are set for users
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_ssh_key }}"
    state: present
  with_items: "{{ users }}"

- name: Ensure sudoers are set
  lineinfile:
    dest: /etc/sudoers.d/ansible
    line: "{{ item.username }} ALL=(ALL) ALL"
    create: yes
    validate: "visudo -cf %s"
    state: present
  with_items: "{{ users }}"
  when: item.sudo
