---
- include: osx.yml
  when: ansible_distribution == "MacOSX"

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Main - Create temp dir
  file:
    path: ~/.tmp
    state: directory

- name: Main - Download oh-my-zsh install script
  get_url:
    url: "https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
    dest: ~/.tmp/zsh_install.sh
    mode: 0777

- name: Main - Check if oh-my-zsh is installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_installation

- name: Main - Install oh-my-zsh
  script: ~/.tmp/zsh_install.sh
  when: not oh_my_zsh_installation.stat.exists

- name: Main - Set .zshrc
  template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: 0644
