---
- name: Check if homebrew is installed
  shell: brew doctor
  register: homebrew_check
  ignore_errors: yes

- name: Install homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: homebrew_check|failed

- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Check installed packages
  shell: brew list
  register: brew_installed_packages

- name: Check installed casks
  shell: brew cask list
  register: brew_installed_casks

- name: Install packages
  homebrew:
    name: "{{ item }}"
    state: present
  when: not item in brew_installed_packages.stdout
  with_items: "{{ brew_packages }}"

- name: Install casks
  homebrew:
    name: "Caskroom/cask/{{ item }}"
    state: present
  when: not item in brew_installed_casks.stdout
  with_items: " {{ brew_casks }}"
