---
- name: Install tmux and dependencies
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - reattach-to-user-namespace
    - tmux

- name: Install .tmux.conf
  template:
    src: tmux.conf.j2
    dest: ~/.tmux.conf
    mode: 0644

- name: Install tmuxinator
  gem:
    name: tmuxinator
    state: present

- name: Upgrade tmuxinator
  gem:
    name: tmuxinator
    state: latest
  tags:
    - upgrade

- name: Install tmuxinator-completion
  homebrew:
    name: homebrew/completions/tmuxinator-completion
    state: present

- name: Ensure EDITOR is set
  lineinfile:
    dest: "{{ shell_rc_path }}"
    line: export EDITOR=vim
