---
- name: OSX - Install vim
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - macvim

- name: Linux (apt) - Install vim
  apt:
    name: vim
    state: present

- name: Main - Install vimrc
  template:
    src: vimrc.j2
    dest: ~/.vimrc

- name: Main - Create necessary folders for pathogen.vim
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.vim/autoload
    - ~/.vim/bundle

- name: Main - Install pathogen.vim
  get_url:
    url: "https://tpo.pe/pathogen.vim"
    dest: ~/.vim/autoload/pathogen.vim

- name: Main - Install plugins
  git:
    repo: "{{ item.repo }}"
    dest: "~/.vim/bundle/{{ item.name }}"
  with_items: "{{ vim_plugins }}"
